version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "99:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - php
  db:
    image: mysql:8
    restart: always
    deploy:
      replicas: 1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3379:3306"
    volumes:
      - ./data/mysql_cnf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password01
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password01
    networks:
      - php

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    deploy:
      replicas: 1
    depends_on:
      - db
    ports:
      - "8181:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password01
      UPLOAD_LIMIT: 1000M
    networks:
      - php

networks:
  php: